[package]
name = "hello-bevyhub"
version = "0.1.0"
edition = "2024"

[dependencies]
bevyhub_template = "0.0.1-rc.2"


[[package.metadata.scene]]
name = "hello-world"
path = "scenes/hello-world.json"
app = "bevyhub_template/my-base-scene"
